### ISSUE TITLE
itemSrcDir

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#1]
Can you explain this parameter?

"a source directory under which Item classes can be found	" 

Item classes <- you mean entity classes? or library classes?

**Comment by no7mks** [comment]
it's like the Entities namespace&directory of ORM system (e.g. doctrine).

In practice, you put your Item classes (like those found in ut/Game.php, ut/ConsoleGame.php) into the src/Items directory of your project (and give them the corresponding namespace).

**Comment by tfe2012** [comment]
Maybe add this information to main page ?

**Comment by no7mks** [comment]
Yes, I have added some notes into the ### Obtaining an ItemManager section
