### ISSUE TITLE
Not equal value

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#10]
$users = $userRepo->scan(
    "#class = :class AND #age >= :minAge AND #name = :name",
    [
        ":class" => "A",
        ":minAge" => 25,
        ":name" => "John",
    ],
);

You add information about =, >=, <= what about not equal? (!=)

**Comment by no7mks** [comment]
condition expressions are not modified and passed through to DynamoDB, so please visit DynamoDB's doc if you would like to know more about complex condition expression

**Comment by tfe2012** [comment]
<> what about condition like this?

**Comment by no7mks** [comment]
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
