### ISSUE TITLE
Scan with condition "condition"

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#11]
Hi, how make same scan using yours library ? 

<img width="909" alt="screen shot 2017-06-22 at 17 35 26" src="https://user-images.githubusercontent.com/8733714/27439707-4055906e-5771-11e7-8d12-2fa556174e68.png">

I try write:

$supplierProduct = $repository->scan(
            "#asin CONTAINS :asin",
            [
                ":asin" => $asin,
            ]
        );

But it return error.

**Comment by no7mks** [comment]
refer to the condition expression doc for how you can create a valid condition expression: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html#ConditionExpressionReference

In your case, there is no operator called "CONTAINS", instead, you should use the contains() function.

Your code should look like:
```php
$supplierProduct = $repository->scan(
"contains(#asin,  :asin)",
[
":asin" => $asin,
]
);
```

**Comment by tfe2012** [comment]
In yours link I don't find "contains" example. 

But thx for help to find solution

**Comment by no7mks** [comment]
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html

**Comment by tfe2012** [comment]
Thx
