### ISSUE TITLE
Support for Aws\Credentials\Credentials ?

### ISSUE THREAD

**Issue by aaronm-cloudtek** [oasmobile/php-dynamodb-odm#3]
Would you consider adding support for Aws\Credentials\Credentials to specify credentials, in place of a ~/.aws/credentials profile? Or will you accept a PR for this?

Thanks!

**Comment by no7mks** [comment]
This is a feature that should be added in the component: oasis/aws-wrappers

I have added support for 'credentials' key in 2.6.0 of that component, and updated the ODM lib to v0.4.20 for that change. So I think you can run a composer update aiming for the latest version and get the support of credentials now

Let me know if this doesn't work, my simple UT suggests okay under my env
