### ISSUE TITLE
Query return only 30 objects

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#4]
Can you add to description, how to change query limits

**Comment by tfe2012** [comment]
Or how Paginate result?

**Comment by no7mks** [comment]
Most, if not all, AWS services use a next-key variable to implement pagination. i.e., you pass a next-key by reference to query functions, with the initial value set to null, and loop whenever this key is set to something other than null by the query functions.

e.g.:

```php
$result = [];
do {
    $page = $im->getRepository(User::class)->query(
        "#hashKey = :hk AND #sortKey > :min",
        [
            ":hk" => "abc",
            ":min" => 10,
        ],
        '',
        $lastKey
    );
    $result = array_merge($result, $page);
} while ($lastKey);
```

**Comment by tfe2012** [comment]
Maybe you can add this information to ODM tutorial ? 

How about pagination?

If you want create data table.

**Comment by no7mks** [comment]
fixed page-size pagination is not directly supported by DynamoDB, nor can it be supported by ODM. (partly bcz DynamoDB's evaluationLimit parameter is not same as returned page size)

check how facebook, twitter and many modern websites handle pagination in their main news feed page. There is no traditional "pagination", but constantly fetching something more, based on a last-fetched-record. This is quite similar to what DynamoDB supports.

So, if you would like to have old-school pagination, try the following methods:
- read all data to the client side and do pagination there (for records count <= 1000)
- try read as many records as page-size suggests, and you will end up having some redundant records. save them somewhere and combine them in the request for next page

**Comment by tfe2012** [comment]
Send query without 'indexName' 

"#hashKey = :hk AND #sortKey > :min",
        [
            ":hk" => "abc",
            ":min" => 10,
        ],
        '',
        $lastKey

It's impossible , you get 

InvalidArgumentException

**Comment by no7mks** [comment]
I'm sorry, it should be an idx name for GSI, or DynamoDbIndex::PrimaryIndex as default

**Comment by tfe2012** [comment]
What about boolean type?

This is my query. But you can't create boolean index in dynamodb console
->query(
                "#done = :done",
                [
                    ":done" => false,
                ],
                'done-index',
                $lastKey
            );

**Comment by no7mks** [comment]
you are right, you can't create boolean types in dynamodb index. and as a result, you can't query for boolean values. However, you can still use scan() with boolean type for non-indexed search.

**Comment by tfe2012** [comment]
Can you give me code example ?

**Comment by no7mks** [comment]
The readme.md already shows simple use of scan() method. 

Furthermore, I am not sure how familiar you know about DynamoDB. I suggest you fully read AWS' DynamoDB's dev-guide first, because that explains a lot more what DynamoDB is and what DynamoDB can do. ODM doesn't offer more than DynamoDB's ability, and many concepts are strongly based on DynamoDB's convention. (Like the difference between query/scan)

**Comment by tfe2012** [comment]
Thx, I find
