### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#7]
Is it any opportunities sort data ? 

Can you give example ?

**Comment by no7mks** [comment]
DynamoDB is not designed to support complicated sorting. However, the indexes are sorted and whenever you query an index, the results are sorted by the indexed attribute(s). Primary Index, GSI and LSI are all sorted. 

`$im->getRepository(User::class)->query(...)` will return sorted data, according to the index you chose. Moreover, sorting can be done in either ascending order or descending order. Please check the parameter for more information.
