### ISSUE TITLE
Helpful commands

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#8]
Hi, maybe it's good idea add helpful commands like: 

ImportFromBackUp
ExportToBackUp
CleanTableData
CreateTablesFromClassAnnotation

What do you think ?

**Comment by no7mks** [comment]
backup and/or restoration of DynamoDB is actually very tricky and is only directly supported in AWS' console (and they only support full non-incremental backup).

create table command is already supported by  odm:schema-tool:create, we also have update & drop commands as well.

cleaning table data is not that straight forward however. I suggest you simply drop&create the table again from command line. If within the code, you can get the repository and call removeAll()

**Comment by tfe2012** [comment]
I got it, thx
