### ISSUE TITLE
Very long saving

### ISSUE THREAD

**Issue by tfe2012** [oasmobile/php-dynamodb-odm#9]
My code looks like :

//point 1
           $list = $itemManager
                ->getItemManager()
                ->getRepository(SupplierProduct::class)
                ->scanAll(
                    "#matched = :matched",
                    [
                        ":matched" => false,
                    ]
                );
// point 2
            foreach ($list as $value) {
                    $value->addSomeParams();
                    $value->version++;
// ponit 3
                    $this->itemManager->flush();
// ponit 4
                }
            }

Script execution time between point 1 and point 2 is about 20s (scan return 15k items) 

And execution time between point 3 and 4 took  15 minutes and no happen anything. 

What I make wrong?

**Comment by no7mks** [comment]
scanAll takes a $parallel parameter which defaults to 1, if you increase this value, more parallel requests will be sent to DynamoDB and this may speed up your scan. Note that your DynamoDB Table's read throughput should be high enough

regarding flushing taking too much time, please check if your class definition contains any CAS field, if so, each item edited is checked before saving. This is a safe approach to avoid data inconsistency problem, trading performance for consistency.

If you would like to ignore the check-and-set behavior temporarily, you can surround your flush like below:

```php
$previousValue = $itemManager->isSkipCheckAndSet();
$itemManager->setSkipCheckAndSet(true);
$itemManager->flush();
$itemManager->setSkipCheckAndSet($previousValue);
```

I will revisit all documentation when I decide to release a stable 1.0 version. So for now, please take this as a trick if you would like to benefit the safety of CAS and do not want to sacrifice performance in some batch editing scenarios

**Comment by tfe2012** [comment]
Is it true, then I make scan, all scanned data are write to ram ? 

If I scan 10k doc, $list variable size is 10k. 

What will be happened if I will have 10 mln item in table ?

**Comment by tfe2012** [comment]
Just added timers. 
// ponit 3
$startTime = time();    
$this->itemManager->flush();
$endTime = time();
// ponit 4

$diff = $endTime - $startTime;

$diff value is 1202 s.  Is  it normal?

**Comment by no7mks** [comment]
15k item when flushed using a concurrency of 10 requests, each writing 25 items, should end in 200s if your connection to aws is fast. 

regarding scan-all, yes, scan all will persist all data retrieved into memory. Pagination can be achieved by either using scan or scanAndRun

**Comment by tfe2012** [comment]
I want update only 1 item, but like I understand when you call flush method , odm update all item from memory?

**Comment by tfe2012** [comment]
If I  use "scan"

$list = $itemManager
                ->getItemManager()
                ->getRepository(Product::class)
                ->scan(
                    "#buyBox = :buyBox",
                    [
                        ":buyBox" => 0,
                    ]
                );

$list return 0 results

If I use "scanAll" I get 11K results

$list = $itemManager
                ->getItemManager()
                ->getRepository(Product::class)
                ->scanAll(
                    "#buyBox = :buyBox",
                    [
                        ":buyBox" => 0,
                    ]
                );

**Comment by tfe2012** [comment]
why?

**Comment by no7mks** [comment]
scan will read all results page by page. Filter expression is applied on each page. If the first page doesn't have any record qualifying the filter expression, you will get an empty set.

**Comment by tfe2012** [comment]
It's not clear for new users:) can you add this information to documentation ? It would be very useful , thx

**Comment by no7mks** [comment]
Actually, this is very clear for DynamoDB users. This lib is not intended to teach how to use DynamoDB. So I guess it's not a good idea to replicate a guide about DynamoDB concept in the ODM documentation.
